# 한국투자증권 API 설정 (KoreaInvestEnv 호환)
# 생성일시: 2025-09-12 14:03:40
# 수정일시: 2025-09-20 16:48:00 (키 매핑 문제 해결)

# 기본 필수 설정 (KoreaInvestEnv 호환 키 이름 사용)
api_key: "PSvqYXFepNCae5F7uVMNfFVu4Cnjpp0mlD5B"
api_secret_key: "ASUqf/aKqFfpyZOPIWuFYShj/36trXKjoFq7kECfJ1JdtIrVQjj5u/O9PbYIgJPy5n0Nzat5eXrxMlfs3UIAxCxxcORvJoTHnBu0dCl6re2G5jQpuzW7He6cAyFgUqVsbfV0cBjv9QaldE13PgAV0msAGl17voOICdhAI5UoNNSjpIi4aKE="
stock_account_number: "63684939"
url: "https://openapi.koreainvestment.com:9443"
is_paper_trading: false

# 기존 키 이름도 호환성을 위해 유지 (simple_server.py debug_tokens에서 사용)
KI_API_KEY: "PSvqYXFepNCae5F7uVMNfFVu4Cnjpp0mlD5B"
KI_SECRET_KEY: "ASUqf/aKqFfpyZOPIWuFYShj/36trXKjoFq7kECfJ1JdtIrVQjj5u/O9PbYIgJPy5n0Nzat5eXrxMlfs3UIAxCxxcORvJoTHnBu0dCl6re2G5jQpuzW7He6cAyFgUqVsbfV0cBjv9QaldE13PgAV0msAGl17voOICdhAI5UoNNSjpIi4aKE="
KI_ACCOUNT_NUMBER: "63684939"
KI_USING_URL: "https://openapi.koreainvestment.com:9443"
KI_IS_PAPER_TRADING: false

# 자동 발급된 토큰들 (KoreaInvestEnv가 관리)
#KI_ACCOUNT_ACCESS_TOKEN: "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ0b2tlbiIsImF1ZCI6IjU0OTc3Mzc5LTAxYTItNDA1Zi1hZGQ1LWNlOWI1ZWU2YjZhMCIsInByZHRfY2QiOiIiLCJpc3MiOiJ1bm9ndyIsImV4cCI6MTc1NzcyMDE3MywiaWF0IjoxNzU3NjMzNzczLCJqdGkiOiJQU3ZxWVhGZXBOQ2FlNUY3dVZNTmZGVnU0Q25qcHAwbWxENUIifQ.KIry7yV2f2cZr4XRneu56liC0RDgbFfKImyDQXmPnJUD9eOqvwsaTA852d2fTZnBrGoFRAzkgJ6WjERcg2zkag"
#KI_WEBSOCKET_APPROVAL_KEY: "7d606de9-7a65-4e37-9d25-62fdb85dabe4"

# 추가 설정 (선택사항)
# USER_AGENT: "Custom User Agent"

# 주의사항:
# - 이 파일은 민감한 정보를 포함하고 있습니다
# - Git에 커밋하지 마세요 (.gitignore에 추가 권장)
# - KoreaInvestEnv가 토큰 만료를 자동으로 관리합니다
