api_key: PSvqYXFepNCae5F7uVMNfFVu4Cnjpp0mlD5B
api_secret_key: ASUqf/aKqFfpyZOPIWuFYShj/36trXKjoFq7kECfJ1JdtIrVQjj5u/O9PbYIgJPy5n0Nzat5eXrxMlfs3UIAxCxxcORvJoTHnBu0dCl6re2G5jQpuzW7He6cAyFgUqVsbfV0cBjv9QaldE13PgAV0msAGl17voOICdhAI5UoNNSjpIi4aKE=
stock_account_number: '63684939'
paper_api_key: ''
paper_api_secret_key: ''
htsid: wdlight
custtype: P
is_paper_trading: false
my_agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like
  Gecko) Chrome/120.0.0.0 Safari/537.36


#domain info  
url: https://openapi.koreainvestment.com:9443
websocket_url: ws://ops.koreainvestment.com:21000
paper_url: https://openapivts.koreainventment.com:29443
paper_websocket_url: ws://ops.koreainvestment.com:31000

#keys.

using_url: https://openapi.koreainvestment.com:9443



#domain info
